PREFIX=/home/eliot/qtbuilds

cmake ../qt5/ -G Ninja -DQT_HOST_PATH=$PREFIX/qt-host -DCMAKE_TOOLCHAIN_FILE=$PREFIX/toolchain.cmake -DQT_FEATURE_xcb=ON -DFEATURE_xcb_xlib=ON -DQT_FEATURE_xlib=ON -DCMAKE_INSTALL_PREFIX=/usr/local/qt6 -DCMAKE_STAGING_PREFIX=$PREFIX/qt-raspi -DQT_QMAKE_TARGET_MKSPEC=devices/linux-rasp-pi3-vc4-g++ -DQT_BUILD_EXAMPLES=FALSE -DQT_BUILD_TESTS=FALSE -DCMAKE_BUILD_TYPE=Release -DQT_QMAKE_DEVICE_OPTIONS=CROSS_COMPILE=aarch64-linux-gnu-
